# Features extraction code

## Requirements

In [1]:
!pip3 install pandas openpyxl numpy

Requirement already satisfied: pandas in /home/maure/Documents/PhD/draw_my_life_study_1/my_venv/lib/python3.12/site-packages (3.0.1)
Requirement already satisfied: openpyxl in /home/maure/Documents/PhD/draw_my_life_study_1/my_venv/lib/python3.12/site-packages (3.1.5)
Requirement already satisfied: numpy in /home/maure/Documents/PhD/draw_my_life_study_1/my_venv/lib/python3.12/site-packages (2.4.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /home/maure/Documents/PhD/draw_my_life_study_1/my_venv/lib/python3.12/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: et-xmlfile in /home/maure/Documents/PhD/draw_my_life_study_1/my_venv/lib/python3.12/site-packages (from openpyxl) (2.0.0)
Requirement already satisfied: six>=1.5 in /home/maure/Documents/PhD/draw_my_life_study_1/my_venv/lib/python3.12/site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

## Imports

In [2]:
import pandas as pd
import openpyxl
import json
import statistics
import numpy as np

## Dataframe creation and general variables

In [3]:
features_df = pd.read_excel("../extracted_features/extracted_features.xlsx")

data_path = "../data/"
valid_participants = features_df['participant_id']

features_df

,participant_id,gender,age,perceived_topic_intimacy_c1,perceived_topic_intimacy_c2,personal_discomfort_c1,personal_discomfort_c2,revealing_personal_information_c1,revealing_personal_information_c2
0,4,M,23,5,4,1.571,1.000,1.25,1.00
1,5,M,20,3,4,1.143,2.429,1.25,2.00
2,6,F,27,4,3,1.143,1.286,1.00,2.75
3,7,F,21,1,3,1.000,1.000,1.75,1.75
4,9,M,26,4,2,1.714,1.286,2.00,1.50
5,11,F,28,2,4,1.000,1.286,1.00,2.25
6,12,F,19,2,5,1.143,2.571,3.25,5.00
7,13,F,19,2,5,1.143,2.429,1.50,3.25
8,14,F,24,4,3,1.000,1.000,3.00,3.00
9,15,M,29,3,4,1.143,2.143,1.50,1.00
10,16,F,24,3,5,1.286,2.286,1.75,3.25
11,17,M,19,3,4,1.286,2.571,1.00,3.00
12,18,M,32,2,4,1.714,2.571,1.75,2.25
13,19,M,35,1,4,1.000,1.286,1.25,1.25
14,20,M,18,4,2,1.143,2.143,2.25,4.00
15,21,M,18,1,4,1.000,2.429,2.50,3.75
16,22,F,23,4,5,1.000,1.286,2.50,3.25
17,23,M,21,3,3,1.000,1.429,2.25,3.00
18,25,F,27,3,4,1.571,3.143,1.50,3.25
19,26,F,25,4,2,1.571,1.143,1.25,2.25
20,28,M,26,4,3,1.571,2.429,2.00,3.25
21,29,M,26,2,4,1.286,1.000,1.00,1.00
22,30,F,22,3,2,1.571,1.286,1.75,1.50
23,31,F,25,1,4,1.000,2.429,1.75,3.50
24,32,F,36,3,5,1.429,3.714,2.75,4.50

## General features

### Activity time

In [4]:
for condition in ["c1", "c2"]:
    activity_time_list = []
    for participant in valid_participants:
        stroke_file_path = data_path + "p" + str(participant) + "/drawing_data/strokes_" + condition + ".json"
        with open(stroke_file_path, "r") as file:
            data = json.load(file)
        activity_time_list.append(round(data["activity_time"], 2))
    new_column_name = "activity_time_" + condition
    features_df[new_column_name] = activity_time_list

## Drawing dynamics features

### Stroke count

In [5]:
for condition in ["c1", "c2"]:
    stroke_count_list = []
    for participant in valid_participants:
        stroke_file_path = data_path + "p" + str(participant) + "/drawing_data/strokes_" + condition + ".json"
        with open(stroke_file_path, "r") as file:
            data = json.load(file)
        stroke_count_list.append(len(data["strokes"]) + len(data["undone_erased_strokes"]))
    new_column_name = "stroke_count_" + condition
    features_df[new_column_name] = stroke_count_list

,participant_id,gender,age,perceived_topic_intimacy_c1,perceived_topic_intimacy_c2,personal_discomfort_c1,personal_discomfort_c2,revealing_personal_information_c1,revealing_personal_information_c2,activity_time_c1,activity_time_c2,stroke_count_c1,stroke_count_c2
0,4,M,23,5,4,1.571,1.000,1.25,1.00,1209.19,1118.29,464,311
1,5,M,20,3,4,1.143,2.429,1.25,2.00,976.01,1007.23,483,318
2,6,F,27,4,3,1.143,1.286,1.00,2.75,849.10,556.19,115,137
3,7,F,21,1,3,1.000,1.000,1.75,1.75,679.11,508.09,157,105
4,9,M,26,4,2,1.714,1.286,2.00,1.50,796.32,564.09,106,83
5,11,F,28,2,4,1.000,1.286,1.00,2.25,967.74,959.02,355,472
6,12,F,19,2,5,1.143,2.571,3.25,5.00,857.95,822.00,314,250
7,13,F,19,2,5,1.143,2.429,1.50,3.25,580.20,718.35,102,107
8,14,F,24,4,3,1.000,1.000,3.00,3.00,877.48,914.74,360,239
9,15,M,29,3,4,1.143,2.143,1.50,1.00,850.13,654.78,177,273
10,16,F,24,3,5,1.286,2.286,1.75,3.25,1098.70,907.17,333,227
11,17,M,19,3,4,1.286,2.571,1.00,3.00,476.37,607.58,191,166
12,18,M,32,2,4,1.714,2.571,1.75,2.25,432.55,415.85,211,154
13,19,M,35,1,4,1.000,1.286,1.25,1.25,435.40,786.98,142,171
14,20,M,18,4,2,1.143,2.143,2.25,4.00,878.54,891.90,244,213
15,21,M,18,1,4,1.000,2.429,2.50,3.75,917.70,1087.92,95,44
16,22,F,23,4,5,1.000,1.286,2.50,3.25,743.96,719.42,110,126
17,23,M,21,3,3,1.000,1.429,2.25,3.00,839.72,835.11,140,147
18,25,F,27,3,4,1.571,3.143,1.50,3.25,656.46,724.80,99,89
19,26,F,25,4,2,1.571,1.143,1.25,2.25,816.80,654.94,209,64
20,28,M,26,4,3,1.571,2.429,2.00,3.25,884.19,924.91,211,111
21,29,M,26,2,4,1.286,1.000,1.00,1.00,822.03,771.04,217,222
22,30,F,22,3,2,1.571,1.286,1.75,1.50,911.42,891.95,154,133
23,31,F,25,1,4,1.000,2.429,1.75,3.50,912.09,1111.55,105,197
24,32,F,36,3,5,1.429,3.714,2.75,4.50,642.52,558.34,143,73

### Stroke length (total, mean, std)

In [6]:
def compute_stroke_length(stroke_points):
        point_coordinates = np.array(stroke_points)

        # Differences between consecutive points
        diffs = np.diff(point_coordinates, axis=0)

        # Euclidian distances between consecutive points
        euclidian_distances = np.sqrt((diffs ** 2).sum(axis=1))

        # Sum all the distances between each consecutive points of the stroke
        total_stroke_length = euclidian_distances.sum()

        return total_stroke_length

In [7]:
for condition in ["c1", "c2"]:
    stroke_total_length_list = []
    stroke_mean_length_list = []
    stroke_std_length_list = []
    
    for participant in valid_participants:
        stroke_file_path = data_path + "p" + str(participant) + "/drawing_data/strokes_" + condition + ".json"
        with open(stroke_file_path, "r") as file:
            data = json.load(file)

        # Extract length of each stroke of participant
        stroke_length_array = []
        for stroke in (data["strokes"] + data["undone_erased_strokes"]):
            stroke_length_array.append(compute_stroke_length(stroke["points"]))

        # Compute total, mean, and std stroke length
        stroke_total_length_list.append(round(sum(stroke_length_array), 2))
        stroke_mean_length_list.append(round(statistics.mean(stroke_length_array), 2))
        stroke_std_length_list.append(round(statistics.stdev(stroke_length_array), 2))
        
    # Add column to dataframe
    stroke_total_length_name = "stroke_total_length_" + condition
    stroke_mean_length_name = "stroke_mean_length_" + condition
    stroke_std_length_name = "stroke_std_length_" + condition
    features_df[stroke_total_length_name] = stroke_total_length_list
    features_df[stroke_mean_length_name] = stroke_mean_length_list
    features_df[stroke_std_length_name] = stroke_std_length_list

features_df

,participant_id,gender,age,perceived_topic_intimacy_c1,perceived_topic_intimacy_c2,personal_discomfort_c1,personal_discomfort_c2,revealing_personal_information_c1,revealing_personal_information_c2,activity_time_c1,activity_time_c2,stroke_count_c1,stroke_count_c2,stroke_total_length_c1,stroke_mean_length_c1,stroke_std_length_c1,stroke_total_length_c2,stroke_mean_length_c2,stroke_std_length_c2
0,4,M,23,5,4,1.571,1.000,1.25,1.00,1209.19,1118.29,464,311,32406.17,69.84,85.95,31294.04,100.62,171.23
1,5,M,20,3,4,1.143,2.429,1.25,2.00,976.01,1007.23,483,318,251620.84,520.95,1473.13,207701.98,653.15,2489.35
2,6,F,27,4,3,1.143,1.286,1.00,2.75,849.10,556.19,115,137,29558.12,257.03,398.05,15112.46,110.31,128.92
3,7,F,21,1,3,1.000,1.000,1.75,1.75,679.11,508.09,157,105,32312.35,205.81,349.62,18139.80,172.76,335.99
4,9,M,26,4,2,1.714,1.286,2.00,1.50,796.32,564.09,106,83,149419.08,1409.61,8492.46,31562.58,380.27,704.23
5,11,F,28,2,4,1.000,1.286,1.00,2.25,967.74,959.02,355,472,28442.45,80.12,83.10,24608.77,52.14,49.55
6,12,F,19,2,5,1.143,2.571,3.25,5.00,857.95,822.00,314,250,25720.26,81.91,150.50,101484.88,405.94,1375.51
7,13,F,19,2,5,1.143,2.429,1.50,3.25,580.20,718.35,102,107,7907.19,77.52,88.66,13350.23,124.77,169.54
8,14,F,24,4,3,1.000,1.000,3.00,3.00,877.48,914.74,360,239,30949.27,85.97,119.74,39453.10,165.08,237.53
9,15,M,29,3,4,1.143,2.143,1.50,1.00,850.13,654.78,177,273,52409.46,296.10,746.82,77535.20,284.01,634.22
10,16,F,24,3,5,1.286,2.286,1.75,3.25,1098.70,907.17,333,227,34750.51,104.36,197.99,25745.55,113.42,140.80
11,17,M,19,3,4,1.286,2.571,1.00,3.00,476.37,607.58,191,166,17151.18,89.80,92.68,18727.74,112.82,187.26
12,18,M,32,2,4,1.714,2.571,1.75,2.25,432.55,415.85,211,154,17499.96,82.94,84.45,8320.21,54.03,30.75
13,19,M,35,1,4,1.000,1.286,1.25,1.25,435.40,786.98,142,171,20296.09,142.93,132.39,18169.60,106.25,101.79
14,20,M,18,4,2,1.143,2.143,2.25,4.00,878.54,891.90,244,213,34659.36,142.05,191.88,30869.12,144.93,187.32
15,21,M,18,1,4,1.000,2.429,2.50,3.75,917.70,1087.92,95,44,24277.74,255.56,634.32,2941.43,66.85,70.34
16,22,F,23,4,5,1.000,1.286,2.50,3.25,743.96,719.42,110,126,17929.51,163.00,299.92,15113.46,119.95,187.63
17,23,M,21,3,3,1.000,1.429,2.25,3.00,839.72,835.11,140,147,38303.81,273.60,450.96,23724.51,161.39,215.26
18,25,F,27,3,4,1.571,3.143,1.50,3.25,656.46,724.80,99,89,10448.03,105.54,54.36,18532.72,208.23,272.50
19,26,F,25,4,2,1.571,1.143,1.25,2.25,816.80,654.94,209,64,28521.24,136.47,195.32,12474.56,194.92,388.51
20,28,M,26,4,3,1.571,2.429,2.00,3.25,884.19,924.91,211,111,235824.64,1117.65,4324.72,154697.10,1393.67,3273.24
21,29,M,26,2,4,1.286,1.000,1.00,1.00,822.03,771.04,217,222,90237.53,415.84,1099.54,40923.65,184.34,248.47
22,30,F,22,3,2,1.571,1.286,1.75,1.50,911.42,891.95,154,133,32197.98,209.08,645.92,19109.62,143.68,146.91
23,31,F,25,1,4,1.000,2.429,1.75,3.50,912.09,1111.55,105,197,64819.34,617.33,1798.30,63777.09,323.74,374.84
24,32,F,36,3,5,1.429,3.714,2.75,4.50,642.52,558.34,143,73,35903.51,251.07,518.44,19436.69,266.26,335.88

### Stroke speed and acceleration (mean and std)

### Stroke pressure (mean, std, slope over time?)

### Temporal drawing behavior

### Editing behavior

## Drawing production features

## Speech dynamics features

### Pitch (mean, std, percentil-based range)

### Loudness (mean, std)

### Voice quality (Jitter, Shimmer, HNR)

### Temporal speaking behavior

## Speech production features (transcript)

## Display and save final features dataframe